INSERT INTO db_mgp.megagames_ref (id, name, type) VALUES (1, 'Административная функция', 'sub');
INSERT INTO db_mgp.megagames_ref (id, name, type) VALUES (2, 'Безопасность', 'sub');
INSERT INTO db_mgp.megagames_ref (id, name, type) VALUES (3, 'Внутренний аудит', 'sub');
INSERT INTO db_mgp.megagames_ref (id, name, type) VALUES (4, 'Закупки и логистика', 'sub');
INSERT INTO db_mgp.megagames_ref (id, name, type) VALUES (5, 'Инфраструктура', 'sub');
INSERT INTO db_mgp.megagames_ref (id, name, type) VALUES (6, 'B2X', 'sub');
INSERT INTO db_mgp.megagames_ref (id, name, type) VALUES (7, 'B2G', 'sub');
INSERT INTO db_mgp.megagames_ref (id, name, type) VALUES (8, 'B2C', 'sub');
INSERT INTO db_mgp.megagames_ref (id, name, type) VALUES (9, 'PR', 'sub');
INSERT INTO db_mgp.megagames_ref (id, name, type) VALUES (10, 'HR', 'sub');
INSERT INTO db_mgp.megagames_ref (id, name, type) VALUES (11, 'Право', 'sub');
INSERT INTO db_mgp.megagames_ref (id, name, type) VALUES (12, 'Финансы', 'sub');
INSERT INTO db_mgp.megagames_ref (id, name, type) VALUES (13, 'Ритейл', 'sub');
INSERT INTO db_mgp.megagames_ref (id, name, type) VALUES (14, 'Кластер "Сохраняй"', 'sub');
INSERT INTO db_mgp.megagames_ref (id, name, type) VALUES (15, 'ФедКК', 'sub');
INSERT INTO db_mgp.megagames_ref (id, name, type) VALUES (16, 'ФКК', 'sub');
INSERT INTO db_mgp.megagames_ref (id, name, type) VALUES (17, 'TeleSale', 'sub');
INSERT INTO db_mgp.megagames_ref (id, name, type) VALUES (18, 'ФТМ', 'sub');
INSERT INTO db_mgp.megagames_ref (id, name, type) VALUES (19, 'Региональное отделение', 'sub');
INSERT INTO db_mgp.megagames_ref (id, name, type) VALUES (20, 'ПБК', 'sub');