INSERT INTO db_mgp.megagames_activity (id, code, `desc`, comment, win, play, password) VALUES (18, 'kviz', 'КВИЗ/ Брехня', null, 6, 2, 'eaxr6s');
INSERT INTO db_mgp.megagames_activity (id, code, `desc`, comment, win, play, password) VALUES (19, 'humancheckers', 'Человеческие Шашки', null, 6, 2, 'wcmvxb');
INSERT INTO db_mgp.megagames_activity (id, code, `desc`, comment, win, play, password) VALUES (20, 'golf', 'Мини гольф', null, 6, 2, 'wlt7pk');
INSERT INTO db_mgp.megagames_activity (id, code, `desc`, comment, win, play, password) VALUES (21, 'velo', 'Велооркестр', null, 4, 2, '2tp9s6');
INSERT INTO db_mgp.megagames_activity (id, code, `desc`, comment, win, play, password) VALUES (22, 'mobracing', 'Командная игра «Гонки на мобильных телефонах»', null, 2, 1, 'oadw77');
INSERT INTO db_mgp.megagames_activity (id, code, `desc`, comment, win, play, password) VALUES (23, 'world', 'Интерактивная зона «Оживающий мир» ', null, 2, 2, 'yu7x7h');
INSERT INTO db_mgp.megagames_activity (id, code, `desc`, comment, win, play, password) VALUES (24, 'game', 'Game-zone', null, 2, 1, 'ovz8r2');
INSERT INTO db_mgp.megagames_activity (id, code, `desc`, comment, win, play, password) VALUES (25, 'megacheckers', 'Горячительные Мегашашки', null, 2, 1, 'br2v04');
INSERT INTO db_mgp.megagames_activity (id, code, `desc`, comment, win, play, password) VALUES (26, 'poligon', 'Мастер-класс по полигональным маскам компьютерных персонажей', null, 6, 6, '9sdtmp');
INSERT INTO db_mgp.megagames_activity (id, code, `desc`, comment, win, play, password) VALUES (27, 'bar', 'Мастер-класс по приготовлению коктейлей', null, 1, 1, 'kr9jz7');
INSERT INTO db_mgp.megagames_activity (id, code, `desc`, comment, win, play, password) VALUES (28, 'fly', 'Мастер-класс по флейрингу', null, 2, 2, '1mbtl0');
INSERT INTO db_mgp.megagames_activity (id, code, `desc`, comment, win, play, password) VALUES (29, 'freeze', 'Крио-бар', null, 1, 1, 'tkiciq');
INSERT INTO db_mgp.megagames_activity (id, code, `desc`, comment, win, play, password) VALUES (30, 'spin', 'Видео Спиннер с оформлением в стилистике Мегафон ', null, 0, 0, 'of3wzq');
INSERT INTO db_mgp.megagames_activity (id, code, `desc`, comment, win, play, password) VALUES (31, 'master', 'Мастер игры ', null, 2, 1, 'sr676m');
INSERT INTO db_mgp.megagames_activity (id, code, `desc`, comment, win, play, password) VALUES (32, 'vr', 'VR очки', null, 1, 1, 'ymk0ao');
INSERT INTO db_mgp.megagames_activity (id, code, `desc`, comment, win, play, password) VALUES (33, 'foto', 'Фотобудка с масками Instagram/ Megagram', null, 0, 0, 'gymn0k');
INSERT INTO db_mgp.megagames_activity (id, code, `desc`, comment, win, play, password) VALUES (34, 'spheroracing', 'Гонки на роботизированных шариках Sphero', '2 часа/ http://picsbox.ru/gonki-rabotizirovannymi-sharami-sphero/', 4, 2, 'wk3ycq');
INSERT INTO db_mgp.megagames_activity (id, code, `desc`, comment, win, play, password) VALUES (35, 'sqracing', 'Гонки на гироскутере – 2 дорожки', ' конусы', 4, 2, 'cqcx5l');